# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QSettings
from PyQt5 import QtCore, QtGui, QtWidgets
from .image_window import ImageWindow
import argparse


parser = argparse.ArgumentParser()
parser.add_argument('-t', '--interval', help='time interval (second)', dest='interval', type=float, default=1000)

args = parser.parse_known_args()[0]

class Login_Window(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 347)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        Form.setFont(font)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.username_lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("")
        self.username_lineEdit.setText("")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.horizontalLayout.addWidget(self.username_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.password_lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.horizontalLayout_2.addWidget(self.password_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.register_pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setObjectName("register_pushButton")
        self.horizontalLayout_3.addWidget(self.register_pushButton)
        self.login_pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setObjectName("login_pushButton")
        self.horizontalLayout_3.addWidget(self.login_pushButton)
        self.exit_pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        self.exit_pushButton.setFont(font)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout_3.addWidget(self.exit_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.label.setText(_translate("Form", "IBAD Crystal Growth Process Analysis System"))
        self.label_2.setText(_translate("Form", "Username:"))
        self.username_lineEdit.setPlaceholderText(_translate("Form", "Please enter your username"))
        self.label_3.setText(_translate("Form", "Password:"))
        self.password_lineEdit.setPlaceholderText(_translate("Form", "Please enter your password"))
        self.register_pushButton.setText(_translate("Form", "Register"))
        self.login_pushButton.setText(_translate("Form", "Login"))
        self.exit_pushButton.setText(_translate("Form", "Exit"))


class LoginWindow(QWidget, Login_Window):
    def __init__(self):
        super(LoginWindow, self).__init__()
        self.setupUi(self)
        self.register_pushButton.clicked.connect(self.register)
        self.login_pushButton.clicked.connect(self.login)
        self.exit_pushButton.clicked.connect(self.exit)
        self.is_true = False

        self.image_window = ImageWindow(args.interval)

        # 获取项目目录的路径
        project_dir = os.path.dirname(os.path.abspath(__file__))

        # 定义相对于项目目录的设置文件路径
        accounts_settings_path = os.path.join(project_dir, 'accounts.ini')
        last_account_settings_path = os.path.join(project_dir, 'last_account.ini')

        # 创建第一个 QSettings 对象，用于连续存储账号和密码
        self.settings_accounts = QSettings(accounts_settings_path, QSettings.IniFormat)
        # self.settings_accounts.clear()

        # 创建第二个 QSettings 对象，用于存储上次使用的账号
        self.settings_last_account = QSettings(last_account_settings_path, QSettings.IniFormat)
        # self.settings_last_account.clear()

        # 从第二个设置文件中读取上次使用的用户名，并自动填充用户名输入框
        last_used_username = self.settings_last_account.value('username')
        if last_used_username:
            self.username_lineEdit.setText(last_used_username)

    def register(self):  # Register
        username = self.username_lineEdit.text()
        password = self.password_lineEdit.text()

        if not username:
            QMessageBox.warning(self, 'Input Error', 'Please enter a username!')
            return

        if not password:
            QMessageBox.warning(self, 'Input Error', 'Please enter a password!')
            return

        # Check if the username already exists in the config file
        existing_username = self.settings_accounts.contains(username)

        if existing_username:
            QMessageBox.warning(self, 'Username Taken', 'This username is already registered. Please choose a different one!')
        else:
            # Save the new username and password pair to the config file
            self.settings_accounts.setValue(username, password)
            QMessageBox.information(self, 'Registration Successful', 'You have registered successfully!')

    def login(self):  # Login
        username = self.username_lineEdit.text()
        password = self.password_lineEdit.text()

        if not username:
            QMessageBox.warning(self, 'Input Error', 'Please enter a username!')
            return

        if not password:
            QMessageBox.warning(self, 'Input Error', 'Please enter a password!')
            return

        saved_password = self.settings_accounts.value(username)

        # Set this variable when login is successful
        if saved_password is not None and saved_password == password:
            # Save the current logged-in username to another config file for auto-fill next time
            self.settings_last_account.setValue('username', username)
            # QMessageBox.information(self, 'Login Successful', 'Login successful!')
            self.is_true = True
            self.image_window.showMaximized()
            self.close()
        else:
            QMessageBox.warning(self, 'Login Failed', 'Incorrect username or password. Please try again!')
            return

    def exit(self):     # 清空
        self.username_lineEdit.clear()
        self.password_lineEdit.clear()

